# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Third Eye' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Third Eye
  pod 'TesseractOCRiOS', '4.0.0'  
  pod 'Firebase/Core'
  pod 'GoogleMobileVision/FaceDetector'
  pod 'lottie-ios'
  pod 'AWSMobileClient', '~> 2.6.13'
  pod 'AWSRekognition'

end
